### ISSUE TITLE
Requesting for dark mode Laravel 11

### ISSUE THREAD

**Issue by MegamiNoBisho** [php-flasher/php-flasher#185]
I'm using Laravel 11 and i don't see any instruction on how to config for dark mode. 
[https://php-flasher.io/laravel/](url)

**Comment by yoeunes** [comment]
Hi @MegamiNoBisho,

Thank you for reaching out, could you please confirm which version of PHPFlasher you are currently using? Is it v1 or v2?

For users of PHPFlasher v1, instructions for configuring dark mode can be found in our v1 documentation here: https://php-flasher.github.io/laravel/#-dark-mode

If you are using PHPFlasher v2, you can try adding the class `fl-dark` to the `<html>` or `<body>` element of your page. This is a preliminary feature and hasn't been thoroughly tested with Laravel 11, but it should ideally enable the dark mode styling.

Please try the above suggestion appropriate to your version and let me know if it works for you.

Looking forward to your response.

Best regards,
Younes

**Comment by yoeunes** [comment]
Hi @MegamiNoBisho,

I hope you’re doing well. I just wanted to check in regarding this issue. Since I haven’t heard back from you, I’ll close it for now to keep our issue tracker organized.

If you’re still experiencing this problem with the latest version of PHPFlasher, please feel free to reopen the issue or create a new one. I’d be more than happy to assist you further.

Thanks.
