### ISSUE TITLE
CVE-2024-44792 (Reserved): Cross Site Scripting (XSS) in PHPFlasher v2.0.1

### ISSUE THREAD

**Issue by rosellarjun** [php-flasher/php-flasher#193]
CVE-2024-44792 (Reserved): This CVE ID has been assigned but is not yet public. PHPFlasher v2.0.1 is vulnerable to Cross Site Scripting (XSS) via the $flasher, flash() helper.

#### Description

PHPFlasher v2.0.1 is vulnerable to Cross Site Scripting (XSS) via the `$flasher` or `flash()` helper. This issue allows for the injection of malicious JavaScript through flash messages.

#### Vulnerability Type
Cross Site Scripting (XSS)

#### Affected Component
- `$flasher` or `flash()` helper/service in PHPFlasher v2.0.1

#### Attack Type
Local

#### Impact
- Code execution is possible due to XSS.

#### Attack Vectors
To exploit this stored XSS vulnerability, you can use string interpolation within the `flash()` helper or service to set a success message. Example payloads:
```php
flash()->success("User '{$user->name}' updated successfully.");
flash("User '{$user->name}' updated successfully.");
$flasher->success("User '{$user->name}' updated successfully.");
```

#### Proof of Concept
Here is a video demonstrating the XSS vulnerability:
[Proof of Concept Video](https://vimeo.com/video/998925577)
Password: 12345jun

#### Discoverer
Arjun P. Rosell

**Comment by yoeunes** [comment]
Hi Arjun, Thank you for raising this issue.

To clarify, the ability to inject HTML or JavaScript through flash messages is an **intentional feature** of PHPFlasher, designed to give developers flexibility in how they style and structure their flash messages. Similar to the `raw` filter in Twig, this feature allows developers to use HTML elements like `<span>` or `<strong>` to customize their messages. 

However, I completely agree that it's important to ensure **sanitization** when dealing with dynamic data, especially when user-generated content is involved.

Here are some examples to illustrate this:

### Example of Safe Usage:
When rendering static content or sanitized inputs, it's perfectly safe to use HTML in flash messages:

```php
// Safe static usage with HTML elements
flash()->success('User profile <strong>updated</strong> successfully!');
```

### Example of Risky Usage:
In cases where user input is directly passed into the flash message without sanitization, it becomes risky:

```php
// Risky usage with unsanitized user input
flash()->success("User '{$user->name}' updated successfully.");
```

If `$user->name` contains malicious code, it could lead to XSS attacks.

### Example of Safe Usage with Sanitization:
To prevent XSS, the developer should sanitize or escape the input before passing it to the flash message:

```php
// Safe usage with sanitized input
$sanitizedUserName = htmlspecialchars($user->name, ENT_QUOTES, 'UTF-8');
flash()->success("User '{$sanitizedUserName}' updated successfully.");
```

In this example, `htmlspecialchars()` ensures that any potentially dangerous characters are safely escaped before being rendered in the flash message.

---

### Next Steps
I’d love to hear your thoughts on how we could improve this further. Since PHPFlasher is designed to allow flexibility, maybe we could explore adding a note to the documentation to remind developers to sanitize inputs when passing dynamic content into flash messages.

Would you be open to contributing by:
1. **Creating a PR** to add this note to the documentation?
2. **Suggesting other potential improvements** to help make this behavior clearer to developers?

Let me know what you think, and thanks again for your contribution!
 
Younes

**Comment by rosellarjun** [comment]
Hi Younes,

Thank you for your detailed response and for acknowledging the importance of sanitization.

I understand that the ability to inject HTML or JavaScript through flash messages is an **intentional feature** designed for flexibility. However, I believe that security should be a top priority, especially when dealing with user-generated content.

While experienced developers may be aware of the need to sanitize inputs, there is a significant risk that less experienced developers might overlook this, leading to potential XSS vulnerabilities.

Additionally, I already have a method to sanitize inputs using Laravel's `e()` helper function, which can be used as follows:
```php
// Safe usage with sanitized input
flash()->success("User '" . e($user->name) . "' your success message here.");
```

I would be happy to contribute by creating a PR to add these notes to the documentation and suggesting other potential improvements but I am currently busy with my capstone project, so it might take some time.

Thank you again for your attention to this matter.

Best regards, 
Arjun P. Rosell

**Comment by yoeunes** [comment]
Hi @arjunrosell, any updates on the issue regarding `CVE-2024-44792` and the potential improvements we discussed?

**Comment by yoeunes** [comment]
Hi Arjun,

I wanted to let you know that i've released a new version of PHPFlasher that includes an `escapeHtml` option. This feature allows developers to control whether HTML content in flash messages should be escaped or rendered as-is. By setting `escapeHtml` to `true`, you can ensure that any HTML tags are properly escaped, which effectively sanitizes the title and message content to prevent potential XSS vulnerabilities.

Given this update, I will be closing the issue for now. If you have any further questions or if the issue persists, please feel free to reopen it or create a new issue.
